### PR TITLE
Handle non-string panic values.

### PR DESCRIPTION
**Pull request by lthibault**
Fixes: https://github.com/thejerf/suture/issues/59

⏱️  Estimated Review Time:  5 minutes
✅  Merge when ready

### CODE REVIEW

**Comment by lthibault** [comment]
@thejerf In an ideal world, I would have renamed `EventServicePanic.PanicMsg` to `PanicVal` and changed its type to `interface{}`, but this is the next best thing.  As far as I can tell, this should preserve backwards compatibility.  But let me know if I'm overlooking some kind of corner-case.

**Comment by thejerf** [comment]
I agree but I can't justify the backwards compatibility break, I think.

If it's configurable then at least you can JSON it yourself if you want to or something.

**Comment by lthibault** [comment]
> I agree but I can't justify the backwards compatibility break, I think.
> 
> If it's configurable then at least you can JSON it yourself if you want to or something.

Sorry, I think I was unclear:  this PR aims to preserve backwards compatibility, _i.e._ it does _not_ change `EventServicePanic`.

**Comment by thejerf** [comment]
Yes, sorry, I was unclear myself. I was agreeing about your perfect world scenario.

Well, it's a good reason to roll a new version. There's been a couple of open issues here that I didn't quite want to roll a new version for but the sum total is worth it. Give me ~1 hour here and you should have a nice solid v4.0.2 tag to work with.

**Comment by thejerf** [comment]
v4.0.2 is out. I think it should be safe, tests all pass, but you know this is tricky code. If anything goes wrong, you know where to find me.

**Comment by lthibault** [comment]
Will do!  Many thanks once again for your help with this.

**Pull request merged**
