### PR TITLE
feat: add EventStart type and send on hook when starting service

### PR DESCRIPTION
**Pull request by erikbohnsack**
In order to get notifications when the services are started, add a `EventStart` and add it to when starting to run the service.

### CODE REVIEW

**Comment by erikbohnsack** [comment]
@thejerf I saw that you missed the notification on the other open PR, so this is a manual ping :sweat_smile:

**Comment by erikbohnsack** [comment]
The CI-error is a warning that is the same for the other event types, not sure what to do about that :thinking: . Any pointers are welcome!

**Comment by thejerf** [comment]
I try to avoid having events that are easy to synthesize yourself. An event start hook is something you can add as a one-off via sending a message at the beginning of serve, and if you want to build it yourself systematically is easily done with 

```
type StartEventService struct {
    suture.Service
    // whatever info about the event you want
}

func (ses StartEventService) Serve(ctx context.Context) {
    // send the event here
    ses.Service.Serve(ctx)
}
```

I'd prefer to keep it out of suture unless there's some value it is bringing that can only be brought from the inside of the main event loop.

**Comment by erikbohnsack** [comment]
@thejerf fair point! Thanks for a concise and clear response!

**Pull request closed without merging**
