### PR TITLE
[WIP] Context support

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
This does not pass the tests.

The following tests hang or fail:
```
TestStoppingSupervisorStopsServices
TestStopAfterRemoveAndWait
TestTheHappyCase
TestNestedSupervisors
TestFailingSupervisors
TestRemoveAndWait
ExampleNew_simple
```

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Seems most tests that use UseStopChan fail, because supervisor Stop() is now blocking. 
Are we ok to remove the use of that?

**Comment by AudriusButkevicius** [comment]
If I make the stop channel on the failedservice 1 buffered, it seems majority of the tests pass.

**Comment by AudriusButkevicius** [comment]
All tests now pass, but the fix for TestCompleteJob is suspicious, as well as the hack to buffer FailedService.stop to work around the use of UseStopChan in tests.

**Comment by thejerf** [comment]
I'm closing this PR because I'm going to pull it from the jcontext branch, but jcontext is based on this branch.

**Pull request closed without merging**
